In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\Datasets\Data.csv")

In [3]:
df

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

In [4]:
df.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [5]:
df.isna().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [6]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1:].values

In [7]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(X, y , test_size=0.2 , random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [9]:
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
y_train = sc.fit_transform(y_train)

In [12]:
x_train

array([[-1.13572795, -0.88685592,  0.67357894,  0.52070558],
       [-0.80630243, -0.00971567,  0.45145467,  0.14531044],
       [ 1.77128416,  1.84743445,  0.24279248, -1.88374143],
       ...,
       [-0.38409993, -1.24886277,  0.84522042,  0.13092486],
       [-0.9232821 , -1.04155299,  1.54693117,  0.8830852 ],
       [ 1.70136528,  1.05824381, -1.20438076, -2.42285818]])

In [13]:
x_test

array([[ 1.20924389,  1.84743445, -0.61878043, -0.28968211],
       [-0.29401214, -0.39528045,  1.39211729,  0.76937061],
       [-0.64629575, -0.88607065,  1.00508258,  1.77019599],
       ...,
       [-0.99857936, -0.74629361,  1.76737267,  1.02146078],
       [ 1.02368993, -0.50992904, -1.64526378, -0.96443434],
       [-0.32090402, -1.13342892, -1.03442205,  0.0651622 ]])

In [14]:
y_train

array([[ 1.15069786],
       [ 0.79540777],
       [-1.30936356],
       ...,
       [ 0.27595724],
       [ 0.49346982],
       [-1.53508417]])

In [15]:
from sklearn.tree import DecisionTreeRegressor
regressor=DecisionTreeRegressor()
regressor.fit(x_train,y_train)

DecisionTreeRegressor()

In [16]:
y_pred=regressor.predict(x_test)

In [17]:
y_pred

array([-1.47997316,  0.49874641,  0.34513914, ...,  0.93846187,
       -1.00918448,  0.48350294])

In [18]:
y_pred = sc.inverse_transform(y_pred.reshape(-1, 1))

In [19]:
y_pred

array([[429.06],
       [462.81],
       [460.19],
       ...,
       [470.31],
       [437.09],
       [462.55]])

In [20]:
from sklearn.metrics import r2_score
print(f'The r2 score is : {r2_score(y_test , y_pred)}')

The r2 score is : 0.9207785915743659
